---
- name: INFORMATION - [Step 01] - Get Date
  set_fact: date_info="{{lookup('pipe','date +%Y%m%d')}}"
  run_once: true
  delegate_to: localhost

- name: INFORMATION - [Step 02] - Set directory for storing the files
  set_fact:
    default_path: "files/backup_config"
    backup_hni_path: "files/backup_config/backup_config_metro_HNI"
  run_once: true
  delegate_to: localhost

- name: INFORMATION - [Step 03] - Create Backup file
  file:
    path: "{{ backup_hni_path }}/{{ inventory_hostname }}.txt"
    state: touch
    mode: "u=rw,g=rw,o=rw"

- name: INFORMATION - [Step 04] - Retrive config information
  junos_cli:
    host: "{{ ansible_host }}"
    user: "{{ juniper_user }}"
    passwd: "{{ juniper_passwd }}"
    cli: "show configuration"
    dest: "{{ backup_hni_path }}/{{ inventory_hostname }}.txt"
    format: text
