---
- hosts: all
  gather_facts: no
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes
  roles:
    - role: ansible_log_rotato
    - role: check_netconf
    - role: get_facts
      
