---
- hosts: all
  gather_facts: false
  strategy: free
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes

  pre_tasks:
    - name: "[VARIABLES] - Set variable for Ansible's log prefix"
      set_fact: log_prefix="stress_test"
      run_once: true
      delegate_to: localhost

  roles:
#    - role: ansible_log_rotato
    - Juniper.junos
    - role: stress_test
      
