---
- hosts: all
  gather_facts: false
  strategy: free
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes
  roles:
#    - role: ansible_log_rotato
    - Juniper.junos
    - role: stress_test
      
