---
- hosts: all
  gather_facts: no
  serial: 100
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes

  pre_tasks:
    - name: "VARIABLES - Set variable for Class of Service name"
      set_fact: class_of_service_name="RW_EXP"
      run_once: true
      delegate_to: localhost

  roles:
    - role: ansible_log_rotato
    - role: check_netconf
    - role: check_cos
