---
- hosts: all
  gather_facts: false
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes
  pre_tasks:
    - name: "[VARIABLES] - Set variable for Ansible's log prefix"
      set_fact: log_prefix="add_cos_auto_snapshot"
      run_once: true
      delegate_to: localhost

  roles:
    - role: ansible_log_rotato
    - role: check_netconf
    - role: add_cos_auto_snapshot
      
