---
- hosts: all
  gather_facts: false
  serial: 100
  connection: local
  vars_prompt:
    - name: juniper_user
      prompt: User
      private: no
    - name: juniper_passwd
      prompt: Password
      private: yes

  pre_tasks:
    - name: "[VARIABLES] - Set variable for Ansible's log prefix"
      set_fact: log_prefix="edit_bfd_ospf"
      run_once: true
      delegate_to: localhost

    - name: "VARIABLES - Set Old minimum-interval value"
      set_fact: old_interval="500"
      run_once: true
      delegate_to: localhost

    - name: "VARIABLES - Set New minimum-interval value"
      set_fact: new_interval="100"
      run_once: true
      delegate_to: localhost

  roles:
    - role: Juniper.junos
    - role: ansible_log_rotato
    - role: check_netconf
    - role: edit_bfd_ospf
