---
- name: CONFIGURATION - [STEP 01] - Set SNMP Name
  junos_config:
#    backup: true
    lines:
      - set snmp name "{{ inventory_hostname }}"
    comment: update config
    provider:
      username: "{{ juniper_user }}"
      password: "{{ juniper_passwd }}"
      host: "{{ ansible_ssh_host }}"
