---
- name: INFORMATION - [STEP 01] - Set interfaces description
  juniper_junos_config:
    load: "merge"
    lines: 
      - "set interfaces {{ item.src_port }} description TO-{{ item.dest_hostname }}---{{ item.dest_sitename }}---{{ item.dest_port }}"
    host: "{{ ansible_host }}" 
    user: "{{ juniper_user }}"
    passwd: "{{ juniper_passwd }}"
    comment: "Set Interfaces description - by Ansible"
  with_items:
    - "{{ interfaces_description }}"

