---
- name: INFORMATION - [Step 01] - Retrive Juniper Facts
  junos_get_facts:
    host: "{{ ansible_host }}"
    user: "{{ juniper_user }}"
    passwd: "{{ juniper_passwd }}"
    savedir: ./files
  register: router_info

- name: INFORMATION - [Step 02] - Print Router information
  debug:
    msg: "{{ router_info.facts.version }}"
