---
- name: CONFIGURATION - [STEP 01] - Pushing Optic.slax script
  junos_scp_file:
    host: "{{ ansible_host }}" 
    user: "{{ juniper_user }}"
    passwd: "{{ juniper_passwd }}"
    local_dir: "{{ role_path }}/files"
    remote_dir: "/var/db/scripts/event/"
    type: "put"
    file: "Optic.slax"
#    logfile={{ log }}

#- name: CONFIGURATION - [Step 02] - Config event Optic
#  junos_install_config:
#    file: "{{ role_path }}/files/Optic.set"
#    host: "{{ ansible_ssh_host }}"    # variable is from inventory file
#    user: "{{ juniper_user }}"        # variable is from inventory file
#    passwd: "{{ juniper_passwd }}"    # variable is from inventory file
#    comment: "Configure Optic"
