---
- name: CONFIGURATION - [STEP 01] - Pushing Optic.slax script
  juniper_junos_command:
    cli: "show configuration | display set"
    logfile: "cli.log"
    dest: "{{ playbook_dir }}/{{ inventory_hostname }}.setconfig.txt"
    format: text
    host: "{{ ansible_host }}" 
    user: "{{ juniper_user }}"
    passwd: "{{ juniper_passwd }}"
