---
- name: INFORMATION - [Step 01] - Set directory for storing the temp and configuration files
  set_fact:
    default_path: "files/tmp/"
  run_once: true
  delegate_to: localhost

- name: INFORMATION - [Step 02] - Create Set Interface Description command
  template:
    src: "{{ role_path }}/templates/rpm.j2"
    dest: "{{ default_path }}/{{ inventory_hostname }}.set"
    backup: yes
  with_items:
    - "{{ interfaces_description }}"

- stat: path="{{ default_path }}/{{ inventory_hostname }}.set.*"
  register: backup

- debug: var=backup.stdout

- name: INFORMATION - [Step 02] - Create Set Interface Description command
  command: "cat {{ backup }}  >> {{ inventory_hostname }}.set" 

#- name: CONFIGURATION - [Step 03] - Set Interface Description
#  juniper_junos_config:
#    load: 'merge'
#    src: "{{ default_path }}/{{ inventory_hostname }}.set"
#    host: "{{ ansible_host }}"    # variable is from inventory file
#    user: "{{ juniper_user }}"        # variable is from inventory file
#    passwd: "{{ juniper_passwd }}"    # variable is from inventory file
#    commit: true
#    comment: "Set Interface Description - by ansible"

- name: INFORMATION - [Step 04] - Clear Temp file
  shell:  "{{ item  }}"
  with_items:
    - "find {{ default_path }}/*.set. -delete"
  run_once: true
  delegate_to: localhost
