---
- name: INFORMATION - [Step 01] - Restore configuration from backup file
  juniper_junos_config:
    load: 'override'
    src: "{{ role_path }}/files/{{ inventory_hostname }}.txt"
    provider:
      user: "{{ juniper_user }}"
      passwd: "{{ juniper_passwd }}"
      host: "{{ ansible_ssh_host }}"
