---
- name: "[ANSIBLE LOGGING] - Create Ansible log for this run"
  shell: "mv {{ playbook_dir}}/logs/ansible.log {{ playbook_dir }}/logs/{{ log_prefix }}-{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.log && touch {{ playbook_dir}}/logs/ansible.log"
  delegate_to: localhost
  run_once: true
