---
- name: "[ANSIBLE LOGGING] - Create Ansible log for this run"
  shell: "mv {{ playbook_dir}}/logs/ansible.log {{ playbook_dir }}/logs/ansible.log-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  delegate_to: localhost
  run_once: true
